### ISSUE TITLE
"Boost volume" functionality

### ISSUE THREAD

**Issue by rastaman111** [yoheimuta/RxMusicPlayer#37]
Hey! Please add the "Boost volume" functionality, here is an example of how it should work

var boostVolume: Bool = false {
        didSet {
            self.audioPlayer.volume = self.boostVolume
                ? 2
                : 1
        }
    }

**Comment by rastaman111** [comment]
New feature

Add more functionality to rewind audio (15, 30) seconds, so that the user can assign it himself how much it would be convenient for him

MPRemoteCommandCenter.shared().skipForwardCommand and
MPRemoteCommandCenter.shared().skipBackwardCommand

**Comment by rastaman111** [comment]
Question.  
I can edit the audio metadata in my application, how can I update all URLs in the player?

**Comment by yoheimuta** [comment]
@rastaman111 Can you write a single subject on a single issue?
"Boost volume" functionality is your main subject on this issue, right? Or, these three are related deeply?

> self.audioPlayer.volume = self.boostVolume

The RxMusicPlayer has the public property of its AVPlayer. 
Isn't it enough to refer to `yourRxMusicPlayer.player.volume` by yourself to implement this feature?

By the way, I'm curious about `volume = 2` because https://developer.apple.com/documentation/avfoundation/avplayer/1390127-volume doesn't mention it.

**Comment by rastaman111** [comment]
> The RxMusicPlayer has the public property of its AVPlayer.
> Isn't it enough to refer to yourRxMusicPlayer.player.volume by yourself to implement this feature?
> 
> By the way, I'm curious about volume = 2 because https://developer.apple.com/documentation/avfoundation/avplayer/1390127-volume doesn't mention it.

these 3 problems do not depend on each other and in order not to create several issues , I asked all in one

**Comment by yoheimuta** [comment]
> Isn't it enough to refer to yourRxMusicPlayer.player.volume by yourself to implement this feature?

I suggested a solution here.
